#!name=Foodie
#!desc=Foodie解锁
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/Plugallery.png
#!author=89996462
^https:\/\/purchase-foodiecn-api\.yiruikecorp\.com\/v1\/purchase\/subscription\/subscriber\/status url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/yiruikecorp.js
hostname = purchase-foodiecn-api.yiruikecorp.com